### ISSUE TITLE
[DocWebPage] Search is not working properly

### ISSUE THREAD

**Issue by skdwriting** [sodafoundation/documentation#108]
**Issue/Feature Description:**
[DocWebPage] Search is not working properly

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Bug in DocWebPage
**How to reproduce, in case of a bug:**
Open docs.sodafoundation.io
search window
enter "tags" and search

Looks like searching only front page, not searching all the pages and if not found, it should say, not found.
**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
NA

**Comment by anvithks** [comment]
On inspecting the website I see that there is an error in the developer console.
![image](https://user-images.githubusercontent.com/19162717/95024812-1f548200-06a3-11eb-86a2-87082b361352.png)

A few months ago Netlify changed all their sites from a .com domain to a .app domain. (read more [here](https://community.netlify.com/t/changes-coming-to-netlify-site-urls/8918))

As per netlify there are no changes required from us but looks like the search plugin may be affected.

I will check this and update.
