### ISSUE TITLE
The link Join the SODA Foundation Slack is broken

### ISSUE THREAD

**Issue by teanth98** [sodafoundation/documentation#149]
**Issue/Feature Description:**   

The link Join the **SODA Foundation Slack** is broken int [this page](https://docs.sodafoundation.io/community/). I have attached the screenshot below.
![image](https://user-images.githubusercontent.com/34156705/111904102-1ac23100-8a6b-11eb-9600-e48b00165f3d.png)

**Why this issue to fixed / feature is needed(give scenarios or use cases):**  

We can redirect to join the slack with the correct URL: [https://sodafoundation.io/slack/](https://sodafoundation.io/slack/)

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**  

I am attaching the screenshot where the URL is currently redirecting.
![image](https://user-images.githubusercontent.com/34156705/111904310-47c31380-8a6c-11eb-8403-c04c9fc5f63f.png)

**Comment by nandan-shah** [comment]
hello, can I fix this issue?

**Comment by anvithks** [comment]
@nandan-shah Please go ahead and raise the PR.

**Comment by nandan-shah** [comment]
can you add a hacktoberfest-accepted label to this PR?
