### ISSUE TITLE
Create the releases page for Isabela release of SODA

### ISSUE THREAD

**Issue by anvithks** [sodafoundation/documentation#166]
**Issue/Feature Description:**
Create the page for Isabela release of SODA and add it to the Releases and Roadmap section.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
To ensure information about  the latest stable release of SODA is available on the SODA foundation documentation website.

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by ArjunGK22** [comment]
@anvithks Hello Sir, Can I know where the change has to be made and what content should be added. So I can work on it. It would be easy if it is explained briefly. Thank You,

**Comment by UtkarshUmre** [comment]
i would like to contribute to resolving this issue if it is still open

**Comment by Kgkunal** [comment]
Hello @anvithks ,

I'd like to volunteer to work on this issue. Creating a dedicated page for the Isabela release of SODA and adding it to the Releases and Roadmap section is important to ensure that users have access to up-to-date information about the latest stable release on the SODA Foundation documentation website.

If there are any specific guidelines or requirements for this task, please let me know. I'm eager to contribute and would appreciate any guidance or additional information to get started.

Thank you...

**Comment by anvithks** [comment]
@UtkarshUmre @Kgkunal Thanks for showing interest in this issue but currently we do not maintain release pages on our documentation website.
We add an entry to the [RELEASES AND ROADMAPS](https://docs.sodafoundation.io/releases/) page and link it to the release notes on GitHub.

This issue is now stale and I will be closing it.

**Comment by Kgkunal** [comment]
@anvithks Thank you for the clarification, 

I appreciate the explanation regarding the documentation process for release information. I understand that this particular issue is now considered stale and will be closed.
