### ISSUE TITLE
Update  the currently supported vendors in delfin user guide

### ISSUE THREAD

**Issue by vineela1999** [sodafoundation/documentation#192]
**Issue/Feature Description:**
In content/guides/user-guides/delfin/dashboard/_index.md the  currently supported vendors given as Dell EMC, Huawei, HPE, Hitachi, IBM.
Need to update with the current added vendors
**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by joseph-v** [comment]
The file <delfin dir>/setup.py, section 'delfin.storage.drivers', contains all the supported drivers

**Comment by shelar1423** [comment]
@joseph-v can i work on this one or is this closed?
