### ISSUE TITLE
Rename OpenSDS Roadmap to SODA Roadmap in documentation 

### ISSUE THREAD

**Issue by nguptaopensds** [sodafoundation/documentation#55]
**Issue/Feature Description:**
https://docs.sodafoundation.io/releases/ page provides link to Project roadmap and it names it OpenSDS Roadmap instead of SODA Foundation Roadmap, need to update

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Update SODA Documentation

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by anvithks** [comment]
Seems to be fixed
