### ISSUE TITLE
Update Join and Contribute page in SODA Documentation

### ISSUE THREAD

**Issue by nguptaopensds** [sodafoundation/documentation#58]
**Issue/Feature Description:**
https://docs.sodafoundation.io/community/ page in SODA Front facing document has Join and Contribute link which still says OpenSDS instead of SODA Foundation, needs to be updated

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Update SODA Documentation

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by anvithks** [comment]
Seems to be fixed.
