### ISSUE TITLE
Update Credits page on front facing SODA Documentation

### ISSUE THREAD

**Issue by nguptaopensds** [sodafoundation/documentation#60]
**Issue/Feature Description:**
https://opensds-docs.netlify.app/credits link not found, needs to be updated

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Update SODA Foundation Documentation

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by anvithks** [comment]
Seems to be fixed.
